{% set name = "brename" %}
{% set version = "2.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/shenwei356/brename/archive/v{{ version }}.tar.gz
  sha256: a16bceb25a75afa14c5dae2248c1244f1083b80b62783ce5dbf3e46ff68867d5

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - brename --help

about:
  home: https://github.com/shenwei356/brename
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A cross-platform command-line tool for safely batch renaming via regular expressions

extra:
  recipe-maintainers:
    - apcamargo
